### ISSUE TITLE
Full chapter citation [FEATURE]

### ISSUE THREAD

**Issue by Jsewill** [BibleBot/BibleBot#143]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like BibleBot to post a full chapter when only a chapter (or chapter range) is specified.

**Describe alternatives you've considered**
None.

**Additional context**
Self explanatory.

**Comment by vypr** [comment]
Hiya.

I've tinkered around with chapter previews when someone writes a verse and chapter, but it didn't get used and wasn't needed all too much. In terms of viewing chapters, you can do things like `John 3:16-` to get John 3:16 and the rest of the chapter from there, same for `John 1:1-`. Something to keep in mind is that there is a limit to how much text Discord will allow to be printed. So posting full chapters is not only something that can't really be done (except in books like Jude or Obadiah maybe), it can be technically taxing as well due to the size of the request and any processing that will need to be done for it.

I'll leave this open for additional comments but I'm not confident in implementing this feature.

In Christ,
Seraphim

**Comment by xsrp** [comment]
No other support has been given for the idea here and on Discord, closing as a result.
