### ISSUE TITLE
Other bots aren't using server defaults when referencing a verse.

### ISSUE THREAD

**Issue by sonnyz1114** [BibleBot/BibleBot#239]
### What happened?

Even with the server version set to CSB, when dyno(discord bot) uses any command to post a verse, it posts it in KJV. I'm setting up an automatic timed daily verse using dyno because dyno can issue timed messages. Thank you.

**Comment by SeraphimRP** [comment]
This is a bit of a double-edged sword. As it stands, BibleBot does not ignore bot messages in any way, meaning that you can use the bot to modify its own preferences, etc. This poses a problem because we don't want servers fighting Dyno constantly to keep the preferences they want. However, we want to make things somewhat convenient for those who use other bots to operate BibleBot for one reason or another.

I'll make an update no later than next Monday which will prevent bots from using preference-related commands and utilize the server's default, unless you have the other bot say `John 1:1 KJV` - which it'll obviously override that default. This will likely include an extension in server default preferences, some formatting options and what have you.

Thank you for reporting the issue!

**Comment by SeraphimRP** [comment]
Resolved with 92f4c9f, bots will utilize server defaults moving forward.
