### ISSUE TITLE
Song of Solomon Seems to Malfunction on KJVA

### ISSUE THREAD

**Issue by PeterPE128** [BibleBot/BibleBot#244]
### What happened?

Bot seems to have an issue with handling Song of Solomon references using King James Version with Apocrypha. ___Might___ be related to #203.
![73F02044-31D2-404B-8936-462427495E64](https://user-images.githubusercontent.com/25531954/147604255-d785471f-03de-4972-9572-8a504c1c21b3.jpeg)

**Comment by SeraphimRP** [comment]
Did some further investigation. While this *is* KJVA specific, it's not the same issue as #203. Like previous issues we've encountered with API.Bible, this one exists because the book name `Song of Songs` (the bot transposes all of this book's abbreviations/translations/variants into this particular book name) is not understood as a book the KJVA has, but `Song of Solomon` as a book name works in a direct test query to API.Bible. I don't know why this is KJVA specific (as the reference works fine in FBV, the other API.Bible version we have) or why this issue even exists in the first place.

The easiest solution is replacing `Song of Songs` in [`src/BibleBot.Backend/Data/book_map.json`](https://github.com/BibleBot/BibleBot/blob/master/src/BibleBot.Backend/Data/book_map.json#L24) with `Song of Solomon`. I'll just have to run some tests to make sure it doesn't break non-API.Bible versions.

---

Query results for `Song of Songs 1:1` to API.Bible (this is what the bot does now):
```json
{
  "data": {
    "query": "Song of Songs 1:1",
    "limit": 100,
    "offset": 0,
    "total": 0,
    "verseCount": 0,
    "verses": []
  },
  "meta": {
    ...
  }
}
```

Query results for `Song of Solomon 1:1` to API.Bible (this is what the bot has to do):
```json
{
  "data": {
    "passages": [
      {
        "id": "SNG.1.1",
        "orgId": "SNG.1.1",
        "bibleId": "de4e12af7f28f599-01",
        "bookId": "SNG",
        "chapterIds": [
          "SNG.1"
        ],
        "reference": "Song of Solomon 1:1",
        "content": "<p class=\"p\"><span data-number=\"1\" data-sid=\"SNG 1:1\" class=\"v\">1</span>The song of songs, which <span class=\"add\">is</span> Solomon’s.</p>",
        "verseCount": 1,
        "copyright": "\n          \n            PUBLIC DOMAIN except in the United Kingdom, where a Crown Copyright applies to printing the KJV. See http://www.cambridge.org/about-us/who-we-are/queens-printers-patent\n        "
      }
    ]
  },
  "meta": {
    ...
  }
}
```
