### ISSUE TITLE
future twitch integration?

### ISSUE THREAD

**Issue by p0xss** [BibleBot/BibleBot#294]
### What would you like to see implemented in BibleBot?

Hi, I was wondering if in the future you guys would consider taking the current discord bot and modifying it in such a way that it could also be a twitch bot? I myself am a twitch streamer and I would most definitely use the bot and I think it would also be beneficial for fellow Christian streamers trying to spread Jesus' love. Just a request, I have no idea how much work or coding it would be to port it from a discord to a twitch bot, but I just thought I would mention the idea as it is something I have been looking for. 
Thanks for your time. 

Sincerely - Eli

**Comment by PeterPE128** [comment]
If we had the dev team to buildout and maintain it, I think it could be within the realm of possibilities. Discord will, however, remain our most important platform for probably a good while.

**Comment by SeraphimRP** [comment]
Given that Twitch chat is effectively a glorified [IRC](https://en.wikipedia.org/wiki/Internet_Relay_Chat), this would end up being a much smaller service that probably wouldn't get as much traction.

From an organizational perspective, it'd be a waste of our already-limited resources. We'd need to have much more scale before we can really begin to consider other platforms. Once we did, I don't anticipate Twitch being on the higher end of priority just because Twitch chat is plaintext, so it'd be difficult to feel like we were providing as effective of an experience to users there.

But hey, if you want to challenge yourself - or if someone else wants to take the torch, you can always try your hand at making your own Twitch bot!
